// import the library
import { library } from '@fortawesome/fontawesome-svg-core';

// import your icons
import {faCheck, faPlus, faEye, faHouse, faUser, faCircleXmark, faCircleCheck, faEnvelope, faLock, faPhone, faCircleUser, faPen, faCircleInfo,
    faCarrot, faAppleWhole, faFish, faShrimp, faBowlFood, faCheese, faCandyCane, faCookieBite, faDrumstickBite, faBurger, faWineGlass,
    faMugSaucer, faMartiniGlassEmpty, faBottleWater, faWhiskeyGlass, faPeopleRoof, faPersonWalking, faPersonRunning, faPersonBiking,
    faGraduationCap, faPeopleCarryBox, faMoneyBillTrendUp, faHandHoldingDroplet, faPersonSwimming, faPersonBreastfeeding, faBed, faChildren,
    faPersonPraying, faHeart, faHeartPulse, faHeartCircleCheck, faWeightScale, faBrain, faTablets, faTooth, faJoint, faSmoking, faUmbrella, 
    faDumbbell, faDog, faCat, faStairs, faStopwatch, faTableTennisPaddleBall, faVolleyball, faBasketball, faFutbol, faBriefcase, 
    faHeadphones, faCamera, faBrush, faCartPlus, faGift, faDesktop, faMobileScreenButton, faMobileButton, faWrench, faScrewdriverWrench, 
    faTrashCan, faPlugCircleXmark, faPlugCircleCheck, faPlugCircleExclamation, faPeace, faBuilding, faSchool, faHospital, faTreeCity, 
    faStore, faChurch, faMountain, faUmbrellaBeach, faMoon, faSun, faCar, faTruck, faPlane, faShip, faMotorcycle} 
    from '@fortawesome/free-solid-svg-icons';

export const iconos = {
    check: faCheck,
    ojo: faEye, 
    plus: faPlus,
    casa: faHouse,
    perfiluser: faUser,
    usuario: faCircleUser,
    mail: faEnvelope,
    candado: faLock,
    telefon: faPhone,
    circuloequis: faCircleXmark,
    circulocheck: faCircleCheck,
    editar: faPen,
    info: faCircleInfo,
    comida1: faCarrot,
    comida2: faAppleWhole,
    comida3: faFish,
    comida4: faShrimp,
    comida5: faBowlFood,
    comida6: faCheese, 
    comida7: faCandyCane,
    comida8: faCookieBite,
    comida9: faDrumstickBite,
    comida10: faBurger,
    bebida1: faWineGlass,
    bebida2: faMugSaucer,
    bebida3: faMartiniGlassEmpty,
    bebida4: faBottleWater,
    bebida5: faWhiskeyGlass,
    grupogente: faPeopleRoof, 
    caminar: faPersonWalking,
    correr: faPersonRunning,
    nadar: faPersonSwimming,
    bici: faPersonBiking,
    estudiar: faGraduationCap,
    ayudar: faPeopleCarryBox,
    ahorrar: faMoneyBillTrendUp,
    donarsangre: faHandHoldingDroplet,
    abrazo: faPersonBreastfeeding,
    dormir: faBed,
    niños: faChildren,
    rezar: faPersonPraying,
    corazon: faHeart,
    corazonpulso: faHeartPulse,
    corazoncheck: faHeartCircleCheck,
    bascula: faWeightScale,
    cerebro: faBrain,
    medicina: faTablets,
    diente: faTooth,
    pesa: faDumbbell,
    cigarro: faJoint,
    cigarro2: faSmoking,
    paraguas: faUmbrella,
    perro: faDog,
    gato: faCat,
    escaleras: faStairs,
    reloj: faStopwatch,
    tennis: faTableTennisPaddleBall,
    voley: faVolleyball,
    basket: faBasketball,
    futbol: faFutbol,
    maleta: faBriefcase,
    musica: faHeadphones,
    camera: faCamera,
    pintar: faBrush,
    comprar: faCartPlus,
    regalo: faGift,
    pantalla: faDesktop,
    movil: faMobileScreenButton,
    movil2: faMobileButton,
    herramienta: faWrench,
    herramienta2: faScrewdriverWrench,
    basura: faTrashCan, 
    enchufecequis: faPlugCircleXmark,
    enchufecheck: faPlugCircleCheck,
    enchufexclamation: faPlugCircleExclamation,
    paz: faPeace,
    edificio: faBuilding,
    colegio: faSchool,
    hospital: faHospital,
    parque: faTreeCity,
    tienda: faStore,
    iglesia: faChurch,
    montaña: faMountain,
    playa: faUmbrellaBeach,
    noche: faMoon,
    sol: faSun,
    coche: faCar,
    camion: faTruck,
    avion: faPlane,
    barco: faShip,
    moto: faMotorcycle,

}